
application:
  jwt:
    secret-key: ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days

spring:
  application:
    name: childmonitoring

  datasource:
    url: jdbc:postgresql://localhost:5432/childmanagement
    username: postgres
    password: benjamin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG